### ISSUE TITLE
[question] 스터디는 몇주로 진행할까요?

### ISSUE THREAD

**Issue by wooyounggggg** [depromeet/clean-architecture-study-12th-team4#3]
> 예시 question issue입니다.

## 질문

스터디를 몇주로 진행하면 좋을까요?

## 연관 주차 및 챕터

#1 
0장

**Comment by LeeJejune** [comment]
매주마다 고정 시간대를 정해서 하는건 어떤가요? ex) 매주 일요일 밤 10시

**Comment by wooyounggggg** [comment]
@LeeJejune 시험 기간 끝나고 구체적으로 일정과 시간대, 방식 정해보시죠 ㅎㅎ
